### ISSUE TITLE
Bug sur le debug

### ISSUE THREAD

**Issue by Jerome-PS** [KiwiHC16/Butineuse#1]
Salut,

J'ai essayé ton firmware. En gros j'ai juste mis JN5169 au lieu de JN5168. Il plante quand il essaye de faire un DGB_vPrintf:
```
BEN: First Trace in app_start.c->main()->Youppee
BEN: JN5168 sur channel 
```
Lorsqu'il essaye d'interpréter le %d. Si je remplace le % par un x, il print (sans insérer la valeur bien sûr) et plante à l'appel suivant (à l'endroit où il doit remplacer un %d par le paramètre...)

Ça t'est arrivé?

**Comment by KiwiHC16** [comment]
"En gros j'ai juste mis JN5169 au lieu de JN5168" Tu veux dire dans les parametres de compilation ?
Jamais eu ce type d erreur.

**Comment by Jerome-PS** [comment]
Juste pour dire que j’ai pris ton code tel quel sans modifs...
Quand je mets VERBOSE (il affiche le nom du fichier et la ligne devant chaque trace), je vois le premier nom de fichier et au lieu de me mettre le numéro de ligne, il freeze pareil...
T’as que des JN5168 ou t’aurais un 69 aussi pour essayer?

**Comment by KiwiHC16** [comment]
C est quoi VERBOSE ? Est ce le mode debug sur UART1 ?
Je ne comprends pas ce que tu fais.
Non je n'ai pas de JN5169 ou alors il faut que je demonte une de mes capteurs mes j'en ai besoin pour mes autres tests pour l'instant.

**Comment by Jerome-PS** [comment]
#define DBG_VERBOSE (ça ajoute le nom du fichier et le numéro de la ligne d'où tu appelles DBG_vPrintf, cf.: fichier dbg.h).
Je veux juste utiliser la fonction DBG_vPrintf, mais ça crashe!
A priori, la lib provoque une Exception IllegalInstruction... 
Bon, ben je pense que je vais utiliser ma propre fonction, la fonction de NXP est a priori inutilisable sur JN5169...

**Comment by KiwiHC16** [comment]
Intéressant le DBG_VERBOSE, je  n'avais pas repéré.

Par contre je ne comprends pas comment  tu souhaites récupérer les logs, utilises tu UART0, la même qui envoie les paquets sniffer ? Comment traites tu les deux flux de données ? Ou alors sa crash avant même que tu démarres le sniff ?

**Comment by Jerome-PS** [comment]
Non, j'ai configuré le debug pour qu'il sorte sur UART1, ce qu'il fait, tant qu'on lui demande d'envoyer une chaîne de caractères constante... Dès qu'il doit faire un boulot du genre remplacer un %d, je vois une exception qui débarque...

**Comment by KiwiHC16** [comment]
Je comprends mieux mais je n'ai pas eu ce problème. Je ne vois pas pourquoi il y aurai une difference entre le 5168 et 5169 sur ce sujet. Un problème de SDK ? Lequel utilises tu ?

**Comment by KiwiHC16** [comment]
Je suis avec JN-SW-4163, je ne sais pas si il y a un lien...

**Comment by Jerome-PS** [comment]
J'utilise le même SDK, les deux différences sont la puce JN5168/JN5169 et le compilateur.
