### ISSUE TITLE
Les messages en moins de 2 à 3 ms sont perdus

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Butineuse#2]
Si deux messages se suivent en moins de 2 à 3 ms alors ils sont perdus.

**Comment by KiwiHC16** [comment]
Si j'enleve les logs, le timing des packets, au8Uart(T/T)xBuffer de 100 à 1000, plus loop sur les paquets radio qui arrivent, j'ai tous les packets sauf les ACK qui sont sous la ms. Il faut que je regarde comment les message radio sont bufferisés.

**Comment by Jerome-PS** [comment]
Tu peux essayer la branche Coordinator [https://github.com/Jerome-PS/JN516xSniffer/tree/Coordinator](https://github.com/Jerome-PS/JN516xSniffer/tree/Coordinator), j'ai ajouté un mode 1MBps.

Il faut maintenant lancer (même sous Linux) 
`python3 Sniff.py /dev/ttyUSB0 -c 20`

Et il y a un menu dans wireshark pour passer à 1Mbps, dis-moi si ça améliore...

**Comment by KiwiHC16** [comment]
Y a bcp de modification, ca va me prendre un peu de temps pour porter cela sur ma version....
C est quoi les crc et beacon ajoutés ?

**Comment by Jerome-PS** [comment]
C'est pour pouvoir envoyer des trames.
Ben pour essayer, t'as juste à changer le JN5169 en JN5168, non?
Parce que si ça ne résout pas le problème, tu vas te faire du boulot pour rien...

**Comment by Jerome-PS** [comment]
Après, je ne sais pas exactement quel est ton objectif, mais ça peut valoir le coup qu'on fusionne les deux projets, quitte à travailler sur des branches différentes pour les ajouts de fonctionnalités qu'on sélectionnerait (comme les traces de debug) avec des #ifdef, ça demandera moins de temps de portage...
